### ISSUE TITLE
Week 5/7 Review Ticket

### ISSUE THREAD

**Issue by JakubPonulak** [JakubPonulak/5_hackers#47]
5 Hackers: Week 5/7 Review Ticket

- Demo of PBL key features - [Mini-Quizzes](https://github.com/JakubPonulak/5_hackers/issues/24), [API Collection](https://github.com/JakubPonulak/5_hackers/issues/48)
- Demo of Github Pages and Jekyll - only presenting and demonstrating using Github pages, Github and PBL web project (no IntelliJ or other IDE, no localhost) - [Link](https://jakubponulak.github.io/5_hackers/)
- Theme using Sassy / Bootstrap - under the hood on CSS usage and capitalizing on Bootstrap features - [Link](https://github.com/JakubPonulak/5_hackers/issues/43)
- Async Operation - runtime and under the hood usage of JavaScript and Fetch - [Link](https://github.com/JakubPonulak/5_hackers/issues/44)
- CRUD in Database - runtime and behind the scenes using CRUD operations - [Link](https://github.com/JakubPonulak/5_hackers/issues/22)

Extra or Replacement Points

- Blueprint illustration/demonstration - [Link](https://github.com/JakubPonulak/5_hackers/blob/main/main.py)
- Formatted Search, Search Bar accessing data from Database - [Link](https://github.com/JakubPonulak/5_hackers/blob/main/crud/templates/crud/search.html)

**Comment by CalissaT** [comment]
Dominators Review: 

Demo of PBL key features - **1**
- I'm very impressed with how your website looks and runs 
- Each subject button and page looks and functions really nicely
- The API collection was unique, the ability to go through the different APIs and each API having their own theme is really good

Demo of Github pages and Jekyll - **1**
- The Jekyll page looks nice, easy to read
- Week 6 Jekyll page is well made
- Maybe in the future put everyone's week 6 in one place so that you don't have to go to different areas to find them

Theme using Sassy/Bootstrap - **0.75** 
- The theme is really good, and the demonstration of CSS skills is very strong
- No SCSS file/sassy code

Async Operation -  **1**
- Looks good, works well on the page

CRUD in database - **1**
- CRUD is functional on the website
- Used it well for the purpose of the website

**Extra Credit**
Blueprints - **1**
- Blueprints are used
- Since you have a lot of pages in the future you'd probably want to use more

Search Bar  - **1**
- Search bar functions on the website well
- Searches emails

Total: **6.75/5**

**Comment by TristanCopley** [comment]
[Dominators' Review Ticket](https://github.com/yqw7/dominators/issues/69)
[Project Highlights Video](https://drive.google.com/file/d/18f9mhhJdXTV4uYa3WYZcfV6ZZ-r3IzMh/view?usp=sharing)
